#!/usr/bin/env bash

sudo apt update
sudo apt upgrade -y
sudo apt install ruby -y
sudo python -m ensurepip --upgrade
sudo apt install python3-pip -y
sudo apt install python3-venv -y
sudo apt install python3-setuptools -y
sudo apt install python3-wheel -y
sudo apt install python3-dev -y
sudo apt install MySQLdb -y
sudo apt install libmysqlclient-dev -y
sudo apt install libssl-dev -y
sudo apt install libffi-dev -y
sudo apt install build-essential -y
pip install sqlalchemy
sudo apt install gcc -y
sudo apt install nodejs -y
sudo apt install npm -y
sudo apt install curl -y

sudo apt install code -y




git config --global user.name "John"
git config --global user.email "makauwanyoike@gmail.com"


git clone https://github.com/alx-tools/Betty.git
sudo ./Betty/install.sh


##
#git add alx-higher_level_programming/* && git commit -m "update" && git push origin master
#git add alx-low_level_programming/* && git commit -m "update" && git push origin master
#git add alx-system_engineering_devops/* && git commit -m "update" && git push origin master
#git add communities/* && git commit -m "update" && git push origin master
##

pipx uninstall Fabric
sudo apt-get install libffi-dev
sudo apt-get install libssl-dev
sudo apt-get install build-essential
sudo apt-get install python3.4-dev
sudo apt-get install libpython3-dev
pipx install pyparsing
pipx install appdirs
pipx install setuptools==40.1.0
pipx install cryptography==2.8
pipx install bcrypt==3.1.7
pipx install PyNaCl==1.3.0
pipx install Fabric3==1.14.post1
