#!/usr/bin/env bash

sudo dnf update
sudo dnf upgrade -y
sudo dnf install ruby -y
sudo python -m ensurepip --upgrade
sudo dnf install python3-pip -y
sudo dnf install python3-venv -y
sudo dnf install python3-setuptools -y
sudo dnf install python3-wheel -y
sudo dnf install python3-dev -y
sudo dnf install MySQLdb -y
sudo dnf install libmysqlclient-dev -y
sudo dnf install libssl-dev -y
sudo dnf install libffi-dev -y
sudo dnf install build-essential -y
pip install sqlalchemy
sudo dnf install gcc -y
sudo dnf install nodejs -y
sudo dnf install npm -y
sudo dnf install curl -y

sudo dnf install code -y




git config --global user.name "John"
git config --global user.email "makauwanyoike@gmail.com"


git clone https://github.com/alx-tools/Betty.git
sudo ./Betty/install.sh


##
#git add alx-higher_level_programming/* && git commit -m "update" && git push origin master
#git add alx-low_level_programming/* && git commit -m "update" && git push origin master
#git add alx-system_engineering_devops/* && git commit -m "update" && git push origin master
#git add communities/* && git commit -m "update" && git push origin master
##

pipx uninstall Fabric
sudo dnf install libffi-devel -y
sudo dnf install openssl-devel -y
sudo dnf install @development-tools -y
sudo dnf install python3-devel -y
sudo dnf install python3-devel -y
pipx install pyparsing
pipx install appdirs
pipx install setuptools==40.1.0
pipx install cryptography==2.8
pipx install bcrypt==3.1.7
pipx install PyNaCl==1.3.0
pipx install Fabric3==1.14.post1
